<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_mastercard</name>
   <tag></tag>
   <elementGuidId>f888fa2d-2e84-473a-b498-19b65d20b728</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>name(&quot;MasterCard&quot;)[count(. | //*[@name = 'MasterCard']) = count(//*[@name = 'MasterCard'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>name(&quot;MasterCard&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MasterCard</value>
   </webElementProperties>
</WebElementEntity>
